-- phpMyAdmin SQL Dump
-- version 4.1.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Giu 30, 2016 alle 22:02
-- Versione del server: 5.6.29-log
-- PHP Version: 5.3.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `my_jingalmera`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `Contatti`
--

CREATE TABLE IF NOT EXISTS `Contatti` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Nome` varchar(30) NOT NULL,
  `Email` varchar(50) NOT NULL,
  `Oggetto` text NOT NULL,
  `Descrizione` text NOT NULL,
  `Data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=12 ;

--
-- Dump dei dati per la tabella `Contatti`
--

INSERT INTO `Contatti` (`id`, `Nome`, `Email`, `Oggetto`, `Descrizione`, `Data`) VALUES
(1, 'FABIO MERAVIGLIA', 'fabiomeraviglia@gmail.com', 'Accipicchia', 'Questo sito Ã¨ fantastico!', '2016-06-30 11:43:38'),
(2, 'FABIO Falso', 'fabiomeraviglia@gmail.com', 'Accipicchia2', 'Questo sito Ã¨ fantastico! ancora', '2016-06-30 11:46:20'),
(9, 'mario', 'mario@gmail.com', 'mario', 'mariommario', '2016-06-30 15:16:25'),
(8, 'AI', 'AI@AI.IA', 'AIAIAIAI<script>alert(1)</script>', 'AIAIAI'' AIAI', '2016-06-30 14:39:17'),
(10, 'Asd', 'dsa@gmail.com', 'Ciao', 'Really', '2016-06-30 15:51:05'),
(11, 'Asd', 'dda', 'Sss', 'Fff', '2016-06-30 19:35:22');

-- --------------------------------------------------------

--
-- Struttura della tabella `Device`
--

CREATE TABLE IF NOT EXISTS `Device` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Categoria` varchar(25) CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `Nome` varchar(255) CHARACTER SET latin1 COLLATE latin1_spanish_ci DEFAULT NULL,
  `Descrizione` text CHARACTER SET latin1 COLLATE latin1_spanish_ci,
  `DatiTecnici` text CHARACTER SET latin1 COLLATE latin1_spanish_ci,
  `Prezzo` text CHARACTER SET latin1 COLLATE latin1_spanish_ci,
  `Immagine` varchar(255) CHARACTER SET latin1 COLLATE latin1_spanish_ci DEFAULT NULL,
  `Offerta` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `id_2` (`ID`),
  KEY `id` (`ID`),
  KEY `category` (`Categoria`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=32 ;

--
-- Dump dei dati per la tabella `Device`
--

INSERT INTO `Device` (`ID`, `Categoria`, `Nome`, `Descrizione`, `DatiTecnici`, `Prezzo`, `Immagine`, `Offerta`) VALUES
(1, 'smartphones', 'LG G4', '-4G PLUS\r\n\r\n-S.O. ANDRIOD 5.0\r\n\r\n-Display 5''\r\n\r\n-Processore Snapdragon HexCore\r\n\r\n-<a href="assistant-supporto-configurazioni-mobile.html">Supporta il servizio SOS Smrtphone</a>', 'Chipset: QualcomSnapDragon 808 Cortex\nProcessore: 1.8Ghz 6 Core\nRam: 3GB\nMemoria: 32GB\nPollici: 5.5\nRisoluzione: 1440x2560 pixels', '19,44 &#8364/mese', 'assets/images/smartphones/g4.jpg', 1),
(2, 'smartphones', 'Samsung Galaxy S6', 'Caratteristiche:\r\n\r\n    Sistema Operativo Android 5.0\r\n    Display 5.1''\r\n    Processore OctaCore (QuadCore 2.1 Ghz + QuadCore 1.5 Ghz)\r\n\r\n-<a href="assistant-supporto-configurazioni-mobile.html">Supporta il servizio SOS Smrtphone</a>', '\r\n\r\nSistema Operativo Android 5.0\r\nDisplay 5.1\r\nProcessore OctaCore (QuadCore 2.1 Ghz + QuadCore 1.5 Ghz)\r\n\r\nTecnologia\r\n\r\n4G cat.6/HSDPA42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\r\n\r\n\r\nConnettivita\r\n\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n\r\n\r\nGPS\r\n\r\nIntegrato\r\n\r\n\r\nDisplay\r\n\r\n5.1 16 Milioni colori Touch\r\n\r\n\r\nFotocamera\r\n\r\n16 Mpixel/Flash\r\n\r\n\r\nMemoria Interna\r\n\r\n32GB\r\n\r\n\r\nProcessore\r\n\r\nOctaCore: (QuadCore 2.1 Ghz+QuadCore 1.5 Ghz)\r\n\r\n\r\nFormato SIM\r\n\r\nNano\r\n\r\n\r\nVideo\r\n\r\nVideo Recorder&Playback\r\n\r\n\r\nMusica\r\n\r\nMP3 Player\r\n\r\n\r\nIn dotazione\r\n\r\nCaricabatteria - Cavo Dati MicroUSB - Auricolare stereo - Guida di riferimento rapido\r\n\r\n\r\nDimensioni\r\n\r\n143,4x 70,5x 6,8 mm\r\n\r\n\r\nPeso\r\n\r\n138 gr.\r\n\r\n\r\nAutonomia(*)\r\n\r\nStand-by fino a 490 ore - Conversazione fino a 1020 min\r\n\r\n', '15 &#8364/mese', 'assets/images/smartphones/galaxy-s6.jpg', 0),
(4, 'smartphones', 'LG X Screen', '\r\nCaratteristiche:\r\n\r\n    4G LTE - NFC\r\n    Sistema Operativo Android 6.0\r\n    Display 4.93'' + Display secondario 1.76''\r\n    Processore Snapdragon™ 410 QuadCore 1.2 GHz\r\n\r\n', '\r\n\r\n4G LTE - NFC\r\nSistema Operativo Android 6.0\r\nDisplay 4.93 + Display secondario 1.76\r\nProcessore Snapdragon™ 410 QuadCore 1.2 GHz\r\n\r\nTecnologia\r\n\r\n4G cat.4/HSDPA42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\r\n\r\n\r\nConnettivita\r\n\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n\r\n\r\nGPS\r\n\r\nIntegrato\r\n\r\n\r\nDisplay\r\n\r\nDisplay 4.93 + Display secondario 1.76\r\n\r\n\r\nFotocamera\r\n\r\nPosteriore da 13 Mpxl con flash e Frontale da 5 Mpx\r\n\r\n\r\nMemoria Interna\r\n\r\n16GB\r\n\r\nSlot Memory Card Micro SD fino a 32GB\r\n\r\n\r\nProcessore\r\n\r\nProcessore Snapdragon™ 410 QuadCore 1.2 GHz\r\n\r\n\r\nFormato SIM\r\n\r\nNano-sim\r\n\r\n\r\nAudio e Video\r\n\r\nVideo Recorder&Playback - MP3 Player - Radio FM\r\n\r\n\r\n\r\nIn dotazione\r\n\r\nCaricabatteria, Cavo dati USB, Manuale d’uso rapido, Auricolare stereo\r\n\r\nDimensioni\r\n\r\n142,6x71,8x7,1 mm\r\n\r\n\r\nPeso\r\n\r\n120 gr.\r\n\r\n ', '269,90 &#8364', 'assets/images/smartphones/xscreen.png', 0),
(3, 'smartphones', 'iPhone 6s', 'Caratteristiche:\r\n\r\n    4GPLUS\r\n    Display Retina HD da 4,7(diagonale) con risoluzione di 1334x750 px\r\n    3D Touch\r\n    Chip A9 con coprocessore di movimento M9 integrato\r\n    Fotocamera iSight da 12 megapixel con Focus Pixels, True Tone Flash e Live Photos\r\n    iOS 9 e iCloud', 'iOS 9 e iCloud\r\nDisplay Retina HD da 4,7(diagonale) con risoluzione di 1334x750 pixel\r\nChip A9 con coprocessore di movimento M9 integrato\r\nFotocamera iSight da 12 megapixel con Focus Pixels, True Tone Flash e Live Photos\r\n\r\nDisplay\r\n\r\nDisplay Retina HD da 4,7 (diagonale) con risoluzione di 1334x750 pixel\r\n3D Touch\r\n\r\n\r\nProcessore\r\n\r\nChip A9 con coprocessore di movimento M9 integrato\r\n\r\n\r\nFotocamera\r\n\r\nFotocamera iSight da 12 megapixel con Focus Pixels, True Tone Flash e Live Photos\r\n\r\n\r\nRegistrazione video\r\n\r\nRegistrazione video 4K a 30 fps, moviola (1080p) a 120 fps\r\n\r\n\r\nVideocamera\r\n\r\nVideocamera FaceTime HD con Retina Flash (foto da 5MP)\r\n\r\n\r\nSensori\r\n\r\nTouch ID di seconda generazione\r\n\r\n\r\nConnettivita\r\n\r\n4G LTE Advanced1 e Wi-Fi 802.11a/b/g/n/ac con tecnologia MIMO\r\n\r\n\r\nSistemaOperativo\r\n\r\niOS 9 e iCloud\r\n\r\n\r\nColori\r\n\r\nColori: argento, oro, grigio siderale, oro rosa', '21,94 &#8364/mese', 'assets/images/smartphones/iphone-6s.png', 1),
(5, 'smartphones', 'Microsoft Lumia 950', '\r\nCaratteristiche:\r\n\r\n    4GPLUS\r\n    Sistema Operativo Windows 10 Mobile\r\n    Display 5.2\r\n    Processore Snapdragon™ 808 HexaCore 1.8 Ghz  - 4G  \r\n\r\n', '    Sistema Operativo Windows 10 Mobile\r\n    Display 5.2\r\n    Processore Snapdragon™ 808 HexaCore 1.8 Ghz  - 4G \r\n\r\nTecnologia\r\n\r\n4G cat.6/HSDPA 42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900\r\n\r\n\r\nConnettivita\r\n\r\nWi-Fi - Bluetooth - Micro USB - NFC \r\n\r\n\r\nGPS\r\n\r\nIntegrato\r\n\r\n\r\nDisplay\r\n\r\n5.2 16 Milioni colori Touch\r\n\r\n\r\nFotocamera\r\n\r\n20 Mpixel/Flash\r\n\r\n\r\nMemoria Interna\r\n\r\n32 GB\r\n\r\n\r\nSlot Memory Card\r\n\r\nMicro SD fino a 2TB\r\n\r\n\r\nProcessore\r\n\r\nHexaCore 1.8 GHz\r\n\r\n\r\nFormato SIM\r\n\r\nNano\r\n\r\n\r\nVideo\r\n\r\nVideo Recorder&Playback\r\n\r\n\r\nMusica\r\n\r\nMP3 Player\r\n\r\n\r\nIn dotazione\r\n\r\n    Caricabatteria standard\r\n    Auricolare stereo \r\n    Cavo Dati  USB Type C \r\n    Manuale d’uso\r\n\r\n\r\nDimensioni\r\n\r\n45x73,2x8,25 mm\r\n\r\n\r\nPeso\r\n\r\n150 grammi\r\n\r\n\r\nAutonomia (*)\r\n\r\nStand-by fino a 275 ore - Conversazione fino a 1080 min.', '599 &#8364', 'assets/images/smartphones/lumia950.jpg', 0),
(6, 'smartphones', 'WIKO Rainbow Lite', '\r\nCaratteristiche:\r\n\r\n    Sistema Operativo Android 5.0\r\n    Display 5''\r\n    Processore QuadCore 1.3 GHz\r\n\r\n', '    Sistema Operativo Android 5.0\r\n    Display 5''\r\n    Processore QuadCore 1.3 GHz\r\n\r\nMusica\r\n\r\nMP3 Player – Radio FM\r\n\r\n\r\nDisplay\r\n\r\nDisplay 5'' 16 Milioni colori Touch\r\n\r\n\r\nConnettivita\r\n\r\nWi-Fi - Bluetooth - Micro USB\r\n\r\n\r\nVideo\r\n\r\nVideo Recorder&Playback\r\n\r\n\r\nFotocamera\r\n\r\n5 Mpixel/Flash\r\n\r\n\r\nMemoria Interna\r\n\r\n8 GB\r\n\r\n\r\nSlot Memory Card\r\n\r\nMicro SD fino a 64GB\r\n\r\n\r\nFormato SIM\r\n\r\nStandard\r\n\r\n\r\nGPS\r\n\r\nIntegrato\r\n\r\n\r\nProcessore\r\n\r\nQuadCore 1.3 GHz\r\n\r\n\r\nIn dotazione\r\n\r\n    Caricabatteria\r\n    Cavo Dati\r\n    Auricolare stereo\r\n    Kit adattatori SIM\r\n    Manuale d’uso\r\n\r\n\r\nDimensioni\r\n\r\n143 x 71,7 x 8,9 mm\r\n\r\n\r\nPeso\r\n\r\n160 gr.\r\n\r\n\r\nAutonomia (*)\r\n\r\nStand-by fino a 360 ore - Conversazione fino a 705 min.\r\n', '99 &#8364', 'assets/images/smartphones/rainbow-lite.jpg', 0),
(7, 'smartphones', 'LG V10', '\r\nDescrizione:\r\n\r\n    4GPLUS\r\n    Sistema Operativo Android 5.1\r\n    Display 5.7 secondario 2.1\r\n    Processore Snapdragon™ 808 HexaCore 1.8 Ghz\r\n\r\n', '\r\nIncluso nella confezione\r\n\r\nCaricabatteria\r\nAuricolare stereo LG QuadBeat 3+\r\nCavo Dati MicroUSB\r\nManuale d’uso rapido', '749,90 &#8364', 'assets/images/smartphones/V10.jpg', 0),
(8, 'smartphones', 'BlackBerry PRIV', '\r\nCaratteristiche:\r\n\r\n    Sistema Operativo Android 5.1\r\n    Display WQHD AMOLED Dual Curved da 5.4'''' e 16:9\r\n    Processore Snapdragon 808 Hexa-Core a 64 bit - Adreno 418\r\n    Fotocamera da 18 Mpxl – Autofocus + anteriore da 2 Mpxl Fixedfocus\r\n\r\n', '\r\n\r\nTecnologia\r\n\r\nFD-LTE 1,2,3,4,7,8,13,17,20, 28 (2100/1900/1800/1700/2600/900/700/700/800/700 MHz) TD-LTE 41 (2500Mhz)\r\nHSPA+ 1,2,4,5/6,8 (2100/1900/1700/850/900 MHz), Dual Carrier 42M\r\nGSM Quad-Band (850/900/1800/1900MHz), GPRS/EDGE Classe 12\r\n\r\n\r\nConnettivita\r\n\r\nDLNA, Wi-Fi 802.11 b/g/n 2.4Ghz Wi-Fi 802.11 ac, a/n 5Ghz 4G Mobile Hotspot, Wi-Fi direct, MIMO, Jack audio 3,5mm,SlimPort con connessione Micro-USB2.0 e uscita video con protocolli: 4K@30fps, HDMI, VGA, DisplayPort 1.1, DisplayPort 1.2, DVI, NFC\r\n\r\n\r\nGPS\r\n\r\nGPS (A-GPS, GLONASS, OTDA) Integrato\r\n\r\n\r\nDisplay\r\n\r\nTouchscreen dual curved 5.4'''', 16:9 - 2560 x 1440 pixel, WQHD amoled, 16 milioni colori 540 DPI, Gorilla® Glass 4\r\n\r\n\r\nFotocamera\r\n\r\nRetro: 18 Megapixel, Autofocus, lenti a 6 elementi, OIS, Dual Flash LED, registrazione video 4K @30fps, 1080p @ 60fps, HDR\r\nFronte: 2 Megapixel, Fixedfocus, registrazione video 720p, Wide Selfie Mode\r\n\r\n\r\nMemoria Interna\r\n\r\n32GB\r\n\r\n\r\nMemoria espandibile\r\n\r\nMicroSD Slot fino a 2TB\r\n\r\n\r\nRAM\r\n\r\n3GB\r\n\r\n\r\nProcessore\r\n\r\nSnapdragon 808 Hexa-Core, 64 bit Adreno 418, 600MHz GPU\r\n\r\n\r\nIn dotazione\r\n\r\nCarica batteria - Cavo Dati MicroUSB - Auricolare stereo\r\n\r\n\r\nDimensioni\r\n\r\n147 x 77.2 x 9.4 mm', '899,90 &#8364', 'assets/images/smartphones/bb-priv.png', 0),
(9, 'smartphones', 'Samsung Galaxy S7 Edge', '\r\nCaratteristiche:\r\n\r\n    Sistema Operativo Android 6.0\r\n    Display 5.5''''\r\n    Processore OctaCore (QuadCore 2.3 Ghz + QuadCore 1.6 Ghz)', '\r\n\r\nTecnologia\r\n\r\n4G cat.9/HSDPA42UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\r\n\r\n\r\nConnettivita\r\n\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n\r\n\r\nGPS\r\n\r\nIntegrato\r\n\r\n\r\nDisplay\r\n\r\n5.5'''' 16 Milioni colori Touch\r\n\r\n\r\nFotocamera\r\n\r\n12 Mpixel/Flash\r\n\r\n\r\nMemoria Interna\r\n\r\n32GB\r\n\r\n\r\nProcessore\r\n\r\nOctaCore: (QuadCore 2.3 Ghz+QuadCore 1.6 Ghz)\r\n\r\n\r\nFormato SIM\r\n\r\nNano\r\n\r\n\r\nVideo\r\n\r\nVideo Recorder&Playback\r\n\r\n\r\nMusica\r\n\r\nMP3 Player\r\n\r\n\r\nIn dotazione\r\n\r\nCaricabatteria - Cavo Dati MicroUSB - Auricolare stereo - Guida di riferimento rapido\r\n\r\n\r\nDimensioni\r\n\r\n150,9x72,6x7,7 mm\r\n\r\n\r\nPeso\r\n\r\n157 gr.\r\n\r\n\r\nAutonomia(*)\r\n\r\nStand-by fino a TBD ore - Conversazione fino a TBD min', '21 &#8364/mese', 'assets/images/smartphones/galaxy-s7-edge.png', 0),
(10, 'smartphones', 'LG K8', '\r\nCaratteristiche:\r\n\r\n    4G LTE - NFC\r\n    Sistema Operativo Android 6\r\n    Display 5''''\r\n    Processore QuadCore 1.3 GHz\r\n\r\n', '\r\nTecnologia\r\n\r\n4G cat.4/HSDPA42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\r\n\r\n\r\nConnettivita\r\n\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n\r\n\r\nGPS\r\n\r\nIntegrato\r\n\r\n\r\nDisplay\r\n\r\n5'''' 16 Milioni colori Touch\r\n\r\n\r\nFotocamera\r\n\r\nPosteriore da 8 Mpxl con flash\r\n\r\n\r\nMemoria Interna\r\n\r\n8GB con Slot Memory Card Micro SD fino a 32GB\r\n\r\n\r\nProcessore\r\n\r\nProcessore QuadCore 1.3 GHz\r\n\r\n\r\nFormato SIM\r\n\r\nNano', '179,90 &#8364', 'assets/images/smartphones/k8.png', 0),
(11, 'smartphones', 'Huawei P9 Plus', '\r\nCaratteristiche:\r\n\r\n    Sistema Operativo Android 6.0\r\n    Display Full HD Amoled da 5.5’’\r\n    Doppia Fotocamera Leica da 12 Mpxl Dual Flash + anteriore da 8 Mpxl\r\n    Processore Kirin 955 - Octa-Core (4x2,5 GHz + 4x1,8 GHz)\r\n', '\r\n\r\nConnettivita\r\n\r\n4G cat.6/HSPA+/EDGE/GPRS Frequenze 850/900/1800/1900Wi-Fi 802.11 a/b/g/n/ac Wi-Fi Direct, Bluetooth 4.2, NFC, Sensore d''impronta, Infrarosso\r\n\r\n\r\nGPS\r\n\r\nGPS Integrato, A-GPS, Glonass, BDS\r\n\r\n\r\nDisplay\r\n\r\nDisplay Full HD Amoled da 5.5’’\r\n\r\n\r\nFotocamera\r\n\r\nDoppia Fotocamera Leica da 12 Mpxl Dual Flash + anteriore da 8 Mpxl\r\n\r\n\r\nMemoria Interna\r\n\r\n64GB, Micro SD fino a 128 GB\r\n\r\n\r\nProcessore\r\n\r\nProcessore Kirin 955 - Octa-Core (4x2,5 GHz + 4x1,8 GHz)\r\n\r\n\r\nIn dotazione\r\n\r\nSmartphone Auricolari stereo - Caricabatteria Cavo USB Type-C - Estrattore SIM Guida rapida\r\n\r\n\r\nDimensioni\r\n\r\n152.3 x 75.3 x 6.98 mm\r\n\r\n\r\nPeso\r\n\r\n162 grammi', '749,90 &#8364', 'assets/images/smartphones/p9-plus.png', 1),
(12, 'smartphones', 'Sony XPERIA X', '\r\nCaratteristiche\r\n\r\n    Sistema Operativo Android 6.0\r\n    Display HD 5''''\r\n    Processore Snapdragon® 650 HexaCore 1.8+1.4 Ghz\r\n    Fotocamera da 23 Mpxl Exmor, anteriore da 13 Mpxl\r\n\r\n', '\r\n\r\nTecnologia\r\n\r\nAbilitato tecnologia 4G/HSDPA 42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900\r\n\r\n\r\nConnettivita\r\n\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n\r\nGPS\r\n\r\nIntegrato\r\n\r\nDisplay\r\n\r\nFull HD da 5'''' 1080p, Display TRILUMINOS\r\n\r\nFotocamera\r\n\r\nPosteriore da 23 Mpixel Exmor, Anteriore da 13 Mpxl\r\n\r\nMemoria\r\n\r\nInterna 3GB - Slot Memory Card Micro SD fino a 200GB\r\n\r\nProcessore\r\n\r\nProcessore Qualcomm® Snapdragon™ 650 Hexa-Core (1.8 GHz + 1.4 GHz)\r\n\r\nVideo\r\n\r\nVideo Recorder&Playback\r\n\r\nMusica\r\n\r\nMP3 Player - Radio FM\r\n\r\nIn dotazione\r\n\r\nAuricolare stereo - Caricabatteria - Cavo dati - Guida di riferimento rapido\r\n\r\nDimensioni\r\n\r\n143,7 x 70,5 x 8,6 mm\r\n\r\nPeso\r\n\r\n165 grammi\r\n\r\nAutonomia\r\n\r\nStand-by fino a 779 ore - Conversazione fino a 790 min\r\n', '629,90 &#8364', 'assets/images/smartphones/xperia-x.png', 0),
(17, 'tablet', 'Apple iPad Pro 9.7" 256 GB ', 'Caratteristiche:\r\n\r\n    Display Retina da 9,7'''' (diagonale) con True Tone e rivestimento antiriflesso\r\n    Chip A9 con architettura a 64 bit di livello desktop\r\n    Sensore di impronte digitali Touch ID\r\n    Fotocamera iSight da 12MP con video a 4K\r\n    Videocamera FaceTime HD (foto da 5MP)', '\r\nDisplay\r\n\r\nRetina Display 9,7''''(diagonale) con True Tone e rivestimento antiriflesso\r\n\r\n\r\nSensori\r\n\r\nimpronte digitali Touch ID\r\n\r\n\r\nProcessore\r\n\r\nChip A9X di terza generazione con architettura a 64 bit di livello desktop\r\n\r\n\r\nFotocamera\r\n\r\niSight da 12MP con video a 4K\r\n\r\n\r\nVideocamera\r\n\r\nFaceTime HD (foto da 5MP)', '1200 &#8364', 'assets/images/tablet/ipadpro9.7.png', 0),
(19, 'tablet', 'Huawei Mediapad T1 10 LTE', '\r\nCaratteristiche:\r\n\r\n    Display 9.6'''' PS\r\n    Sistema Operativo Android™ 4.4\r\n    Processore Snapdragon™ 200 QuadCore 1.2 GHz \r\n\r\n', '\r\nConnettivita\r\n\r\nLTE, HSDPA+ 42.2Mbps/HSUPA 5.76/, Wi-Fi 802.11b/g/n, Bluetooth 3.0\r\n\r\n\r\nDisplay\r\n\r\n9.6'''' (1280x800) IPS 16M di colori\r\n\r\n\r\nVideo/Audio/Picture\r\n\r\n2 Fotocamera da 5 Mpx e VGA Lettore multimediale - MP3, WAV, 3GP, AAC, AAC+ e-AAC+, JPG, PNG,GIF, BMP, WMV, H264, Mpeg4, 1080p/30fps\r\n\r\n\r\nMemoria\r\n\r\n8GB (espandibile fino a 64GB)\r\n\r\n\r\nProcessore\r\n\r\nQuad-core 1.2GHz\r\n\r\n\r\nSistemaOperativo\r\n\r\nAndroidTM 4.4 KitKat\r\n\r\n\r\nApplicazioni\r\n\r\nGoogle Mobile Services, Youtube, E-mail, GPS e A-GPS, SMS, Invio e ricezione, chiamata voce.\r\n\r\n\r\nIn dotazione\r\n\r\nCaricabatteria - Manuale d’uso\r\n\r\nDimensioni\r\n\r\n248,5 x 150 x8,3 mm\r\n\r\n\r\nPeso\r\n\r\n433 grammi\r\n\r\n\r\nAutonomia (*)\r\n\r\nStand-by fino a 300h\r\n\r\n', '249,90 &#8364', 'assets/images/tablet/huaweimediapadt1.jpg', 0),
(20, 'tablet', 'Acer ICONIA W4 821', '\r\nCaratteristiche:\r\n\r\n    Display 8'''' (1280x800) IPS\r\n    Sistema Operativo Windows 8.1 + Office Home & Students 2013\r\n\r\n', '\r\nConnettivita\r\n\r\nHSDPA 21.2/HSUPA 5,76/,Wi-Fi Direct 802.11 a/b/g/n, Bluetooth 4.0 - Chiamata voce\r\n\r\n\r\nDisplay\r\n\r\n8'''' (1280x800) IPS\r\n\r\n\r\nVideo/Audio/Picture\r\n\r\n5 Mpx A/F + 2 Mpx frontale, Lettore multimediale, MP3, WAV, 3GP, AAC, AAC+, e-AAC+, JPG, PNG,GIF, BMP, WMV, DivX/AVI\r\n\r\n\r\nMemoria\r\n\r\n32GB, 2GB RAM\r\n\r\n\r\nProcessore\r\n\r\nIntel Atom Quad-Core 1.8GHz\r\n\r\n\r\nSistemaOperativo\r\n\r\nWindows 8.1 + Office Home & Students 2013\r\n\r\n\r\nApplicazioni\r\n\r\nOffice Home & Students 2013, E-mail, GPS/A-GPS, SMS/MMS Invio e ricezione\r\n\r\n\r\nIn dotazione\r\n\r\nCaricabatteria - Guida di riferimento rapido\r\n\r\n\r\nDimensioni\r\n\r\n218.9 x 134.9 x 10.75 mm\r\n\r\n\r\nPeso\r\n\r\n420 grammi\r\n\r\n\r\nAutonomia (*)\r\n\r\n4960 mAh / durata 8h', '349,90 &#8364', 'assets/images/tablet/acericoniaw4.jpg', 1),
(23, 'tablet', 'Alcatel Pixi3 10 ', '\r\nCaratteristiche:\r\n\r\n    Display 10,'''',1280x800\r\n    Android 5.1\r\n    Connetività Hsdpa 21 e chiamata voce\r\n    Doppia fotocamera, 2 Mpxl + VGA\r\n', '\r\n\r\nConnettivita\r\n\r\nMediateKMT8321 Quad-Core da 1.3 GHz\r\n\r\n\r\nDisplay\r\n\r\nDisplay 10,1 ,1280x800\r\n\r\n\r\nFotocamera\r\n\r\nFotocamera (Front: 0.3 Mpxl Back: 2 Mpxl)\r\n\r\n\r\nMemoria\r\n\r\nInterna 8GB (espandibile fino a 64GB)1GB di Ram\r\n\r\n\r\nProcessore\r\n\r\nMediateKMT8321 Quad-Core da 1.3 GHz\r\n\r\n\r\nLettore multimediale\r\n\r\naac, amr, awb, mp3, ogg, wav, DivX, XviD, MPEG4, VP8, H.263, H.264\r\n\r\n\r\nIn dotazione\r\n\r\nCaricabatteria - Connettore dati USB - Manuale d''uso\r\n\r\n\r\nDimensioni\r\n\r\n255x155x8,9 mm.\r\n\r\n\r\nPeso\r\n\r\n365 grammi\r\n\r\n\r\nAutonomia: (*)\r\n\r\nStand-by fino a 350h, 70 ore in chiamata', '139,90 &#8364', 'assets/images/tablet/alcatelpixi3.jpg', 0),
(25, 'networking', 'ZyXEL Repeater Wi-Fi AC750', '\r\nCaratteristiche:\r\n\r\n    Funzionamento simultaneo a 2.4 e 5 GHz\r\n    Velocità di trasmissione fino a 750 Mbps\r\n    Compatibilità Wi-Fi b/g/n a 2.4 GHz e Wi-Fi n/ac a 5 GHz\r\n    Associazione al modem in modalità WPS\r\n\r\n', '\r\n\r\nStandard Wi-Fi\r\n\r\n802.11 a / b / g / n / ac\r\n\r\nVelocità Wi-Fi\r\n\r\n300 Mbps * (2,4 GHz), 450 Mbps * (5 GHz) Ricezione: 300 Mbps * (2,4 GHz), 450 Mbps * (5 GHz)\r\n\r\nSicurezza Wi-Fi\r\n\r\n64/128 bit WEP, WPA / WPA2, WPA-PSK / WPA2-PSK\r\n\r\nCaratteristiche operative\r\n\r\nModalità Ripetitore, Modalità AP, Wi-Fi Protected Setup (WPS), Wi-Fi Multimedia (WMM),Selezione automatica dei canali, Programmazione senza fili, Gestione di potenza di uscita senza fili,Filtraggio degli indirizzi MAC, Modalità di impostazione di copertura.\r\n\r\nSoftware\r\n\r\nAggiornamento del firmware online\r\n\r\nSpecifiche hardware\r\n\r\nLAN: 10/100 Mbps One Ethernet RJ-45 porta con auto MDI / MDIX supporto\r\n\r\nDimensioni\r\n\r\n(LxPxA): 46,5 x 62,3 x 90,9 mm\r\n\r\nPeso\r\n\r\n98 g\r\n\r\nAmbiente operativo\r\n\r\nTemperatura: 0 ° C a 40 ° C (32 ° F a 104 ° F) Umidità: 10% a 90% (senza condensa)\r\n', '49,90 &#8364', 'assets/images/networking/zixelrepeater.png', 1),
(26, 'networking', 'TIM Modem Wi-Fi Car Pack 4G', '\r\nCaratteristiche:\r\n\r\n    Modem WI-FI CarPack4G\r\n    Codice PIN promozionale per 6 mesi di Servizi Assistenza ACI Global\r\n    Alimentatore da rete\r\n    Alimentatore da auto\r\n\r\n', '\r\n\r\nTecnologia\r\n\r\n4G - DC-HSDPA - HSPA+ - HSDPA - HSUPA - EDGE/GPRS\r\n\r\n\r\nFrequenze\r\n\r\n4G: 800/1800/2600 Mhz, download fino a 100Mbps, upload fino a 40Mbps\r\nDC-HSDPA: 900/2100 Mhz, download fino a 42.2Mbps\r\nHSPA+: 900/2100 Mhz, download fino a 21.1 Mbps\r\nHSDPA: 900/2100 Mhz, download fino a 14.4 Mbps\r\nHSUPA: 900/2100 Mhz, upload fino a 5.76 Mbps\r\nEDGE/GPRS: 850/900/1800/1900 Mhz\r\n\r\n\r\nContenuto della Confezione\r\n\r\nModem 4G Wi-Fi - TIM Card con 1 euro di traffico prepagato incluso - Alimentatore da rete - Alimentatore da auto - Cavetto USB - Guida rapida – Card con PIN ACI Global per usufruire della Promozione\r\n\r\n\r\nRequisiti di Sistema\r\n\r\nLa compatibilità è totale per tutti i dispositivi certificati Wi-Fi (802.11b/g/n).\r\n', '99,90 &#8364', 'assets/images/networking/timmodemwifi.png', 0),
(27, 'networking', 'AVM FRITZ!WLAN Repeater', '\r\nCaratteristiche:\r\n\r\n    Estende la portata wireless fino a 1750 Mbit/s\r\n    WPS: lo installi premendo un pulsante\r\n    Compatibile con i modem Wi-Fi di TIM\r\n    Porta LAN Gigabit\r\n    5 anni di garanzia\r\n\r\n', '\r\nStandard Wi-Fi e velocità\r\n\r\n802.11ac (1.300 Mbit/s), 802.11n (450 Mbit/s), 802.11g/a (54 Mbit/s) e 802.11b (11 Mbit/s)\r\n\r\nSicurezza Wi-Fi\r\n\r\nWPA2, WPA, WPS\r\n\r\nCaratteristiche operative\r\n\r\nAssistente per browser e software per semplificare la configurazione\r\n\r\nDimensioni\r\n\r\n(L x H x P): circa 76,5 x 155 x 62,6 mm\r\n\r\nPeso\r\n\r\n151 g circa\r\n\r\nContenuto della confezione\r\n\r\nWireless Range Extender,Cavo Ethernet,Guida rapida\r\n', '2,5 &#8364/mese', 'assets/images/networking/fritzrepeater.png', 0),
(29, 'smartliving', 'Samsung Galaxy Gear S con SIM', '<a href = "smartlife-device.html"> Clicca qui per i dettagli </a>', 'Orologio Multifunzione Intelligente\r\nDisplay 2'' curved SuperAMOLED\r\nProcessore DualCore 1GHz\r\nCertificazione IP67\r\n\r\nConnettivita\r\n\r\nHSDPA 21Mbps/UMTS/EDGE/GPRS - Wi-Fi - Bluetooth - **Micro USB\r\n\r\n\r\nFrequenze\r\n\r\n2G: 900/1800 - 3G: 900/2100\r\n\r\n\r\nDisplay\r\n\r\nTouch da 2”\r\n\r\n\r\nFormato SIM \r\n\r\nNano\r\n\r\n\r\nMemoria interna\r\n\r\n4GB*\r\n\r\nAltro\r\n\r\nNotifiche, Chiamate, SMS, S Health,Lettore musicale, Meteo, Navigatore, Comandi vocali, Running\r\nDownload ulteriori applicazioni tramite il Samsung Gear Apps\r\n\r\n\r\nIn dotazione:\r\n\r\n** Supporto per la carica Micro USB - Carica batteria - Guida di riferimento rapido\r\n\r\n\r\nDimensioni\r\n\r\n39,9 x 58,1 x 12,5 mm\r\n\r\n\r\nPeso\r\n\r\n84 gr.\r\n\r\n\r\nBatteria\r\n\r\n300mAh', '349,99 &#8364', 'assets/images/tvesmartliving/samsunggalaxygears.jpg', 0),
(30, 'smartliving', 'Samsung Smart TV 50" + Soundbar con TIMvision ', '\r\nCaratteristiche:\r\n\r\n    Modello 50JU6400 - 50''\r\n    Ultra HD - 4K 3840 x 2160\r\n    Soundbar HW-J250 inclusa\r\n    TIMvision incluso\r\n', '\r\nNon disponibile', '26,08 &#8364/mese', 'assets/images/tvesmartliving/smarttv50.png', 0),
(31, 'smartliving', 'Beats Solo2 On-Ear Headphones ', '\r\nCaratteristiche:\r\n\r\n    Peso 205 grammi\r\n    Larghezza 156 mm\r\n    Cavo RemoteTalk™\r\n\r\n', 'Peso 205 gr.\r\n\r\nLarghezza 156 mm\r\n\r\nCavo RemoteTalk™\r\n\r\nDimensioni\r\n\r\n156 mm (larghezza)\r\n\r\n\r\nPeso\r\n\r\n205 gr.\r\n\r\n\r\nContenuto della confezione\r\n\r\nCavo RemoteTalk™, Custodia da viaggi', '199,90 &#8364', 'assets/images/tvesmartliving/beatsheadphones.jpg', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
